# https://symfony.com/doc/current/validation.html#validation-constraints
# https://symfony.com/doc/current/validation/groups.html
App\Domain\DTO\LoginUserDTO:
    properties:
        userName:
            - NotBlank:
                message: Please fill in your username or email.
            - Regex:
                # Expected format: nickname containing between 3 and 15 characters or email address
                # (nickname with letters, numbers, "-", "_") alphanumeric characters ([\w-] or [\p{Xan}-_] or [[:alnum:]-_] works) with unicode flag u
                # https://www.pcre.org/current/doc/html/pcre2pattern.html
                # https://stackoverflow.com/questions/2432868/php-regex-word-boundary-matching-in-utf-8
                pattern: '/^([\w-]{3,15})$|^[^\W][a-zA-Z0-9_]+(\.[a-zA-Z0-9_]+)*\@[a-zA-Z0-9_]+(\.[a-zA-Z0-9_]+)*\.[a-zA-Z]{2,4}$/u'
                message: Please use a valid username format<br>A nickname or email is expected!


        password:
            - NotBlank:
                message: Please fill in your password.
            - Regex:
                # Expected format: plain-text password containing between 8 and 20 characters
                # (password with at least 1 special, 1 number, 1 upper and 1 lower letter)
                pattern: '/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[\W]).{8,20}$/'
                message: Please use a valid password format.
