# https://symfony.com/doc/current/validation.html#validation-constraints
# https://symfony.com/doc/current/validation/groups.html
App\Domain\DTO\RenewPasswordDTO:
    properties:
        userName:
            - NotBlank:
                message: Please fill in your username or email.
        passwords:
            - NotBlank:
                message: Please fill in your password.
            - Regex:
                pattern: '/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[\W]).{8,20}$/' # Expected format for plain-text password: between 8 and 20 characters
                message: Please use a valid password format.
