# https://symfony.com/doc/current/validation.html#validation-constraints
# https://symfony.com/doc/current/validation/groups.html
App\Domain\DTO\RequestNewPasswordDTO:
    properties:
        userName:
            - NotBlank:
                message: Please fill in your username or email.