# https://symfony.com/doc/current/validation.html#validation-constraints
# https://symfony.com/doc/current/validation/groups.html
App\Domain\DTO\UpdateProfileAvatarDTO:
    properties:
        avatar:
            - File:
                  maxSize: 100k
                  maxSizeMessage: The file is too large ({{ size }} {{ suffix }}). Allowed maximum size is {{ limit }} {{ suffix }}.
            - Image:
                  mimeTypes:
                      - image/pjpeg
                      - image/jpeg
                      - image/gif
                      - image/png
                      # The use of a svg sanitizer service is necessary to accept this image type.
                      #- image/svg+xml
                  mimeTypesMessage: This file is not a valid image.
                  minWidth: 80
                  minWidthMessage: The image width is too small ({{ width }}px). Minimum width expected is {{ min_width }}px.
                  minHeight: 80
                  minHeightMessage: The image height is too small ({{ height }}px). Minimum height expected is {{ min_height }}px.
        removeAvatar:
            - Type:
                type: bool
                message: A technical error happened! Existing image can not be removed.
        cropJSONData:
            - Type:
                type: string
                message: A technical error happened! Invalid data type is used to upload this image.
            # Upgrade is necessary to use JSON validator: https://symfony.com/blog/new-in-symfony-4-3-json-validation
            #- Json:
                #message: A technical error happened! Invalid data are used to upload this image.
