# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app_website_name: '%env(WEBSITE_NAME)%'
    app_swift_mailer_sender_email: '%env(MAILER_SENDER_EMAIL)%' # admin email
    app_swift_mailer_sender_name: '%env(MAILER_SENDER_NAME)%' # admin email name
    # PHP paths retrieved with parameter bag:
    app_images_upload_directory: '%kernel.project_dir%/public/assets/images/uploads'
    app_avatar_image_upload_directory: '%app_images_upload_directory%/avatars'
    app_trick_image_upload_directory: '%app_images_upload_directory%/tricks'
    # Twig paths:
    app_twig_assets_directory: 'assets'
    app_twig_image_directory: '%app_twig_assets_directory%/images/'
    app_twig_image_upload_directory: '%app_twig_image_directory%uploads/'
    app_twig_avatar_upload_directory: '%app_twig_image_upload_directory%avatars/'
    app_twig_trick_upload_directory: '%app_twig_image_upload_directory%tricks/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

        # setup special, global autowiring rules
        bind:

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Domain/Entity,Kernel.php,Tests,Utils/Command,Utils/Traits,Utils/Database/Migrations}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    # add a simple PSR3 logger as a service
    App\Action\:
        resource: '../src/Action'
        tags: ['controller.service_arguments']
        arguments:
            $logger: '@Symfony\Component\HttpKernel\Log\Logger'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # add form handler when creating a new trick
    App\Action\Admin\CreateTrickAction:
        tags: ['controller.service_arguments']
        arguments:
            $formHandlers: ['@App\Service\Form\Handler\CreateTrickHandler', '@App\Service\Form\Handler\AjaxDeleteImageHandler']

    # add form handler when deleting a particular image
    App\Action\Admin\AjaxDeleteImageAction:
        tags: ['controller.service_arguments']
        arguments:
            $formHandler: '@App\Service\Form\Handler\AjaxDeleteImageHandler'

    # add trick deletion without form and form handler
    App\Action\Admin\AjaxDeleteTrickAction:
        tags: ['controller.service_arguments']

    # add form handler when calling login
    App\Action\Admin\LoginAction:
        tags: ['controller.service_arguments']
        arguments:
            $formHandler: '@App\Service\Form\Handler\LoginHandler'

    # add form handler when renewing password
    App\Action\Admin\RenewPasswordAction:
        tags: ['controller.service_arguments']
        arguments:
            $formHandler: '@App\Service\Form\Handler\RenewPasswordHandler'

    # add form handler when requesting new password
    App\Action\Admin\RequestNewPasswordAction:
        tags: ['controller.service_arguments']
        arguments:
            $formHandler: '@App\Service\Form\Handler\RequestNewPasswordHandler'

    # add form handler when creating a new user account
    App\Action\Admin\RegisterAction:
        tags: ['controller.service_arguments']
        arguments:
            $formHandler: '@App\Service\Form\Handler\RegisterHandler'

    # add form handler when updating a user avatar or account (profile)
    App\Action\Admin\UpdateProfileAction:
        tags: ['controller.service_arguments']
        arguments:
            $formHandlers: ['@App\Service\Form\Handler\UpdateProfileAvatarHandler', '@App\Service\Form\Handler\UpdateProfileInfosHandler']

    # add form handler when updating a trick
    App\Action\Admin\UpdateTrickAction:
        tags: ['controller.service_arguments']
        arguments:
            $formHandlers: ['@App\Service\Form\Handler\UpdateTrickHandler', '@App\Service\Form\Handler\AjaxDeleteImageHandler']

    # add custom unchanged (not updated) trick listener
    App\Service\Event\Listener\UnchangedTrickListener:
        tags:
            - { name: kernel.event_listener, event: form.unchanged }

    # add custom form subscriber
    App\Service\Event\Subscriber\FormSubscriber:

    # add custom DTO mapper
    App\Service\Form\DataMapper\DTOMapper:

    # add login handler
    App\Service\Form\Handler\LoginHandler:

    # add trick creation handler
    App\Service\Form\Handler\CreateTrickHandler:

    # add image deletion handler
    App\Service\Form\Handler\AjaxDeleteImageHandler:

    # add register handler
    App\Service\Form\Handler\RegisterHandler:

    # add renew password handler
    App\Service\Form\Handler\RenewPasswordHandler:
        arguments:
            $emailConfigFactory: '@App\Service\Mailer\Email\EmailConfigFactory'

    # add request new password handler
    App\Service\Form\Handler\RequestNewPasswordHandler:
        arguments:
            $emailConfigFactory: '@App\Service\Mailer\Email\EmailConfigFactory'

    # add update profile avatar handler
    App\Service\Form\Handler\UpdateProfileAvatarHandler:

    # add update profile infos handler
    App\Service\Form\Handler\UpdateProfileInfosHandler:

    # add (trick) image to crop creation/update type
    App\Service\Form\TypeToEmbed\ImageToCropType:
        arguments:
            $dataMapper: '@App\Service\Form\DataMapper\DTOMapper'

    # add (trick) video infos creation/update type
    App\Service\Form\TypeToEmbed\VideoInfosType:
        arguments:
            $dataMapper: '@App\Service\Form\DataMapper\DTOMapper'

    # add user update profile avatar type
    App\Service\Form\Type\Admin\UpdateProfileAvatarType:
        arguments:
            $formSubscriber: '@App\Service\Event\Subscriber\FormSubscriber'

    # add user update profile infos type
    App\Service\Form\Type\Admin\UpdateProfileInfosType:
        arguments:
            $formSubscriber: '@App\Service\Event\Subscriber\FormSubscriber'

    # add trick update type
    App\Service\Form\Type\Admin\UpdateTrickType:
        arguments:
            $formSubscriber: '@App\Service\Event\Subscriber\FormSubscriber'

    # add EmailConfigFactory
    App\Service\Mailer\Email\EmailConfigFactoryInterface: '@App\Service\Mailer\Email\EmailConfigFactory'

    # add Twig custom template renderer
    App\Service\Templating\TemplateRendererInterface: '@App\Service\Templating\TwigTemplateRenderer'
    App\Service\Templating\TemplateBlockRendererInterface: '@App\Service\Templating\TwigTemplateRenderer'

    # add unused images deletion command which can be combined with cron job
    App\Utils\Command\DeleteUnusedImageCommand:
        public: false
        tags: ['console.command']

    # add "preg_replace" function
    App\Utils\Templating\StringReplaceTwigExtension:
        public: false
        tags: ['twig.extension']

    # add "uuid_encode" filter
    App\Utils\Templating\UuidTwigExtension:
        public: false
        tags: ['twig.extension']

    # add ResultSetMappingBuilder as a service for native queries
    Doctrine\ORM\Query\ResultSetMappingBuilder:

    # add PSR3 logger as default logger for actions (controllers)
    Symfony\Component\HttpKernel\Log\Logger:
        arguments: ['critical','%kernel.project_dir%/var/log/dev.log']

    # add options resolver
    Symfony\Component\OptionsResolver\OptionsResolver:
